language: "ru"    # en, ru
lives:
  # Количество жизней (сердец) по умолчанию для нового игрока
  default: 10

  # Команда, которая будет выполнена, если у игрока закончатся все жизни.
  # В команде можно использовать плейсхолдер %player%, который заменится на ник игрока.
  command: "say Игрок %player% лишился всех жизней!"

database:
  # Имя файла базы данных SQLite.
  # Файл будет создан в папке плагина, если он не существует.
  file: "players.db"
