name: h1
version: '${project.version}'
main: com.BlackMinecraft.h1.H1
api-version: '1.18'
authors: [ b0b0b0 ]
website: https://black-minecraft.com/
commands:
  h1:
    description: Команды плагина H1.
    usage: /h1 <give|reload>