name: h1
version: '1.0.5'
main: com.BlackMinecraft.h1.H1
api-version: '1.18'
authors: [ b0b0b0 ]
website: https://black-minecraft.com/
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:6.2.1
commands:
  h1: